spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: usr
    password: pass

  jpa:
    hibernate:
      ddl-auto: create

notification:
  url: http://localhost:8181/notification
